apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: janus-gpt-collection
  description: A collection of Backstage Golden Path Templates for Janus-IDP
spec:
  type: url
  targets:
    - https://github.com/janus-idp/software-templates/blob/main/templates/github/spring-boot-backend/template.yaml
